version: '3.3'
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  elastic:
    image: elastic/elasticsearch:6.4.3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1 
        hard: -1 
    expose:
      - 9200
    ports: 
      - "9200:9200"
  kibana:
    image: elastic/kibana:6.4.3
    ports:
      - "5601:5601" 
    volumes:
      - ./kibana:/usr/share/kibana/config
  redis:
    image: redis:latest
    expose: 
    - 6379
    ports:
      - "6379:6379"
  python_backend:
    build: ./backend
    expose: 
      - 5000
    ports:
      - "5000:5000"
    volumes:
      - ./backend/code:/app
  react_frontend:
    build: ./frontend
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/reactApp/front/front:/front 
